// AUTO-GENERATED by build_deploy.js — do not edit by hand. See CACHING.md.
// Content-hashed assets ⇒ cache-first is always safe (new content = new URL). index.html (the mutable
// entry point) is network-first so a deploy's new hashed URLs are picked up; hashed assets are
// immutable so they're served from cache instantly (fast, incl. the big walk-data files). No manual
// CACHE_NAME bump: this name is derived from the asset set and old caches are dropped on activate.
const CACHE_NAME = 'sahitya-fe3e15901c';
const ASSETS = ["app.de5eb62881.js","axis-manifest.5b29286de9.js","flagged-wrong.b771d3697a.js","pratipadika_endings.8fcd363513.js","quiz-items.5ba173a31f.js","reading-nav.1d8a42d71b.js","samasa-peel.a8f1f18f36.js","site-config.c490c1f550.js","tutorial-data-ramodanta.30cf84c40d.js","tutorial-manifest.31d4aca853.js","walk-data-RMD-1.86f2526a61.js","walk-data-RMD-2.8c52b690f8.js","walk-data-RMD-3.ab3ea63714.js","walk-data-RMD-4.7290399286.js","walk-data-RMD-5.3fccbe52a0.js","walk-data-RMD-6.173d5b2410.js","walk-data-RMD-7.425a91af57.js","walk-manifest.74adc67cbf.js"];
const HASHED = /\.[0-9a-f]{10}\.(js|json|css)$/;   // immutable content-hashed filenames
const SHELL = ['./', './index.html', './translit.js', './sync.js', './NotoSansSiddham.woff2', './scratchpad.html', './docx-import.js', './scratchpad-sync.js'];

self.addEventListener('install', e => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE_NAME).then(c => c.addAll(SHELL)).catch(() => {}));
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    // drop any OTHER cache version outright
    for (const k of await caches.keys()) if (k !== CACHE_NAME && k.startsWith('sahitya-')) await caches.delete(k);
    // prune stale hashed files from the live cache (old app.<oldhash>.js etc. no longer shipped)
    const cache = await caches.open(CACHE_NAME);
    const keep = new Set([...ASSETS, 'index.html', '']);
    for (const req of await cache.keys()) {
      const base = new URL(req.url).pathname.split('/').pop();
      if (HASHED.test(base) && !keep.has(base)) await cache.delete(req);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  const base = url.pathname.split('/').pop();
  // Immutable hashed asset (or the fixed-name Siddhaṃ font binary) → cache-first (fast; never stale).
  if (HASHED.test(base) || base === 'NotoSansSiddham.woff2') {
    e.respondWith(caches.match(e.request).then(hit => hit || fetch(e.request).then(res => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE_NAME).then(c => c.put(e.request, copy)); }
      return res;
    })));
    return;
  }
  // Navigation / index.html / manifest.json / anything else → network-first, cache fallback (offline).
  e.respondWith(fetch(e.request).then(res => {
    const copy = res.clone(); caches.open(CACHE_NAME).then(c => c.put(e.request, copy)).catch(() => {});
    return res;
  }).catch(() => caches.match(e.request).then(hit => hit || caches.match('./index.html'))));
});
